[package]
name = "api-router"
version = "0.1.0"
edition = "2021"

[dependencies]
smol = "2"
async-channel = "2"
futures-lite = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytes = "1.0"
url = "2.0"
async-tls = "0.12"
rustls = "0.20"
webpki-roots = "0.22"
log = "0.4"
env_logger = "0.11"
thiserror = "1"
dashmap = "5"
once_cell = "1.19"
